name: libresult-test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build libresult
      run: |
        sudo apt-get install meson ninja
        meson build
        cd build
        ninja

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      run: |
        sudo apt-get install meson ninja
        meson build
        cd build
        ninja test
